
#ifndef __DEFINES_H
#define __DEFINES_H

#define SCREEN_WIDTH  640
#define SCREEN_HEIGHT 480

#define MOVE_SPEED 500
#define JUMP_FORCE 14
#define GRAVITY 1300

#define PLAYER_RADIUS 30

#define BALL_RADIUS 30
#define BALL_STARTING_VELOCITY 50

#endif // __DEFINES_H
